id: QmXiK7FCnuS2uqX2ScpGaPFQzszJ6oVWwHfpKXwFH7R3Gb
description: Returns a socket url to the matched channel
tags: []
source: .
trigger:
    type: pub-sub
    channel: asdf
    local: false
execution:
    timeout: 10s
    memory: 10MB
    call: asdfasdf
