id: QmPHzHkehroSJUJcvNd8MFn4RBgJeYBTGNabKrkLiK9xZY
description: ""
tags: []
source: libraries/asdfasdf
trigger:
    type: https
    method: GET
    paths:
        - /
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: asdf
