id: Qmaj2jFuwmWJ7H7EooFBdaz7NNB6SfDz1h9oqk3MkpQB2K
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /asdfasasdfasdf
domains:
    - GeneratedDomain
execution:
    timeout: 10s
    memory: 10MB
    call: ping
